### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by ChristopherThompsonUT** [KJRoby/fourblockgame#1]
Consider adding requirements.txt to install pygame for those who have not already installed it. Below is the file that achieves this purpose
[requirements.txt](https://github.com/KJRoby/fourblockgame/files/11228840/requirements.txt)

Fun little python program, btw

**Comment by KJRoby** [comment]
Done, thanks Chris, still new to using git and GitHub for anything but downloading different projects so I'm trying to get used to all this. I'm making another build from the ground up to see if I can solve SRS implementation earlier before all the other features, this build is pretty much on hold until then.
